language: node_js
node_js:
  - '0.10'
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'npm install -g bower grunt-cli'
# Default Dependency Management : npm install (http://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Dependency-Management)
# Default Test Script : npm test (http://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Default-Test-Script)

after_success:
    'npm run-script deploy'
